services:
  - type: web
    name: ai-study-buddy
    env: node
    plan: free
    buildCommand: |
      npm install
      npm run build --prefix frontend
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
